version: "3.4"

services:
  database:
    image: mariadb:latest
    ports:
      - ${DATABASE_HOST}:${DATABASE_PORT}:3306
    # volumes:
    #   - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    restart: always

  counter:
    image: redis:latest
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 150M --save 900 1
    # volumes:
    #   - ./redis:/data:rw
    restart: always
    deploy:
      resources:
        limits:
          memory: 200M
